services:
  backend:
    image: sachinbhandari/classroom-attendance-backend:latest
    container_name: attendance-backend
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/classroom_attendance?serverTimezone=UTC
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: sachinbhandari/classroom-attendance-frontend:latest
    container_name: attendance-frontend
    depends_on:
      - backend
    environment:
      DISPLAY: host.docker.internal:0.0
      LIBGL_ALWAYS_INDIRECT: "1"
      BACKEND_URL: http://backend:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"