sonar.projectKey=classroom-attendance
sonar.projectName=Classroom-Attendance-Management-System
sonar.projectVersion=1.0

sonar.sources=common/src/main/java,backend/src/main/java,frontend/src/main/java
sonar.java.binaries=common/target/classes,backend/target/classes,frontend/target/classes

sonar.host.url=http://127.0.0.1:9000