sonar.projectKey=Classroom-Attendance-Management-System
sonar.projectName=Classroom-Attendance-Management-System
sonar.projectVersion=1.0
sonar.sources=backend/src/main/java/util,backend/src/main/java/services,backend/src/main/java/security,backend/src/main/java/handler,backend/src/main/java/backend.exception
sonar.java.binaries=backend/target/classes
sonar.host.url=http://localhost:9000