sonar.projectKey=your_key
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}

sonar.sources=frontend/src/main/java

sonar.inclusions=\
**/frontend/admin/*.java,\
**/frontend/student/*.java,\
**/frontend/teacher/*.java,\
**/frontend/AppLayout.java,\
**/frontend/ClassRow.java,\
**/frontend/StudentRow.java,\
**/frontend/TeacherRow.java,\
**/frontend/UserRow.java