-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               11.5.2-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for classroom_attendance
CREATE DATABASE IF NOT EXISTS `classroom_attendance` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE `classroom_attendance`;

-- Dumping structure for table classroom_attendance.localization_strings
CREATE TABLE IF NOT EXISTS `localization_strings` (
                                                      `key` varchar(150) NOT NULL,
    `value` text NOT NULL,
    `language` varchar(10) NOT NULL,
    PRIMARY KEY (`key`,`language`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table classroom_attendance.localization_strings: ~965 rows (approximately)
REPLACE INTO `localization_strings` (`key`, `value`, `language`) VALUES
	('auth.forbidden.role', 'ለዚህ ሚና ፍቃድ የሎትም: {role}', 'am'),
	('auth.forbidden.role', 'ليست لديك صلاحية لهذا الدور: {role}', 'ar'),
	('auth.forbidden.role', 'Forbidden for role: {role}', 'en'),
	('auth.forbidden.role', 'Ei oikeuksia roolille: {role}', 'fi'),
	('auth.forbidden.role', 'Ingen behörighet för rollen: {role}', 'sv'),
	('auth.login.error.invalidCredentials', 'የተሳሳተ መረጃ ተሰጥቷል', 'am'),
	('auth.login.error.invalidCredentials', 'بيانات الدخول غير صحيحة', 'ar'),
	('auth.login.error.invalidCredentials', 'Invalid username or password', 'en'),
	('auth.login.error.invalidCredentials', 'Virheellinen käyttäjänimi tai salasana', 'fi'),
	('auth.login.error.invalidCredentials', 'Ogiltigt användarnamn eller lösenord', 'sv'),
	('auth.login.error.requiredPassword', 'የይለፍ ቃል ያስፈልጋል', 'am'),
	('auth.login.error.requiredPassword', 'كلمة المرور مطلوبة', 'ar'),
	('auth.login.error.requiredPassword', 'Password is required', 'en'),
	('auth.login.error.requiredPassword', 'Salasana vaaditaan', 'fi'),
	('auth.login.error.requiredPassword', 'Lösenord krävs', 'sv'),
	('auth.login.error.requiredUsername', 'የተጠቃሚ ስም ያስፈልጋል', 'am'),
	('auth.login.error.requiredUsername', 'اسم المستخدم مطلوب', 'ar'),
	('auth.login.error.requiredUsername', 'Username is required', 'en'),
	('auth.login.error.requiredUsername', 'Käyttäjänimi vaaditaan', 'fi'),
	('auth.login.error.requiredUsername', 'Användarnamn krävs', 'sv'),
	('auth.login.failed', 'መግባት አልተሳካም: {status} {body}', 'am'),
	('auth.login.failed', 'فشل تسجيل الدخول: {status} {body}', 'ar'),
	('auth.login.failed', 'Login failed: {status} {body}', 'en'),
	('auth.login.failed', 'Kirjautuminen epäonnistui: {status} {body}', 'fi'),
	('auth.login.failed', 'Inloggning misslyckades: {status} {body}', 'sv'),
	('auth.login.password', 'የይለፍ ቃል', 'am'),
	('auth.login.password', 'كلمة المرور', 'ar'),
	('auth.login.password', 'Password', 'en'),
	('auth.login.password', 'Salasana', 'fi'),
	('auth.login.password', 'Lösenord', 'sv'),
	('auth.login.submit', 'ግባ', 'am'),
	('auth.login.submit', 'تسجيل الدخول', 'ar'),
	('auth.login.submit', 'Sign in', 'en'),
	('auth.login.submit', 'Kirjaudu', 'fi'),
	('auth.login.submit', 'Logga in', 'sv'),
	('auth.login.subtitle', 'ለመቀጠል ይግቡ', 'am'),
	('auth.login.subtitle', 'سجّل الدخول للمتابعة', 'ar'),
	('auth.login.subtitle', 'Log in to continue', 'en'),
	('auth.login.subtitle', 'Kirjaudu sisään jatkaaksesi', 'fi'),
	('auth.login.subtitle', 'Logga in för att fortsätta', 'sv'),
	('auth.login.title', 'እንኳን በደህና መጡ', 'am'),
	('auth.login.title', 'مرحباً بعودتك', 'ar'),
	('auth.login.title', 'Welcome back', 'en'),
	('auth.login.title', 'Tervetuloa takaisin', 'fi'),
	('auth.login.title', 'Välkommen tillbaka', 'sv'),
	('auth.login.username', 'የተጠቃሚ ስም', 'am'),
	('auth.login.username', 'اسم المستخدم', 'ar'),
	('auth.login.username', 'Username', 'en'),
	('auth.login.username', 'Käyttäjänimi', 'fi'),
	('auth.login.username', 'Användarnamn', 'sv'),
	('auth.not.authenticated', 'አልተገባችሁም', 'am'),
	('auth.not.authenticated', 'غير مصرح لك بالدخول', 'ar'),
	('auth.not.authenticated', 'Not authenticated', 'en'),
	('auth.not.authenticated', 'Ei kirjautunut sisään', 'fi'),
	('auth.not.authenticated', 'Inte inloggad', 'sv'),
	('auth.parse.failed', 'የመግቢያ መልስ መተርጎም አልተቻለም', 'am'),
	('auth.parse.failed', 'تعذر تحليل استجابة تسجيل الدخول', 'ar'),
	('auth.parse.failed', 'Failed to parse login response', 'en'),
	('auth.parse.failed', 'Kirjautumisvastauksen jäsentäminen epäonnistui', 'fi'),
	('auth.parse.failed', 'Kunde inte tolka inloggningssvar', 'sv'),
	('auth.signup.failed', 'መመዝገብ አልተሳካም: {status} {body}', 'am'),
	('auth.signup.failed', 'فشل إنشاء الحساب: {status} {body}', 'ar'),
	('auth.signup.failed', 'Signup failed: {status} {body}', 'en'),
	('auth.signup.failed', 'Rekisteröinti epäonnistui: {status} {body}', 'fi'),
	('auth.signup.failed', 'Registrering misslyckades: {status} {body}', 'sv'),
	('common.app.title', 'የክፍል ተማሪ መገኘት ስርዓት', 'am'),
	('common.app.title', 'نظام حضور الطلاب', 'ar'),
	('common.app.title', 'Classroom Attendance Management System', 'en'),
	('common.app.title', 'Luokkahuoneen Läsnäolon Hallintajärjestelmä', 'fi'),
	('common.app.title', 'Klassrummets Närvarosystem', 'sv'),
	('common.attendance.absent', 'አልተገኘም', 'am'),
	('common.attendance.absent', 'غائب', 'ar'),
	('common.attendance.absent', 'Absent', 'en'),
	('common.attendance.absent', 'Poissa', 'fi'),
	('common.attendance.absent', 'Frånvarande', 'sv'),
	('common.attendance.excused', 'ተሰርዟል', 'am'),
	('common.attendance.excused', 'معذور', 'ar'),
	('common.attendance.excused', 'Excused', 'en'),
	('common.attendance.excused', 'Vapautettu', 'fi'),
	('common.attendance.excused', 'Ursäktad', 'sv'),
	('common.attendance.present', 'ተገኝቷል', 'am'),
	('common.attendance.present', 'حاضر', 'ar'),
	('common.attendance.present', 'Present', 'en'),
	('common.attendance.present', 'Läsnä', 'fi'),
	('common.attendance.present', 'Närvarande', 'sv'),
	('common.button.back', 'ተመለስ', 'am'),
	('common.button.back', 'رجوع', 'ar'),
	('common.button.back', 'Back', 'en'),
	('common.button.back', 'Takaisin', 'fi'),
	('common.button.back', 'Tillbaka', 'sv'),
	('common.button.cancel', 'ይቅር', 'am'),
	('common.button.cancel', 'إلغاء', 'ar'),
	('common.button.cancel', 'Cancel', 'en'),
	('common.button.cancel', 'Peruuta', 'fi'),
	('common.button.cancel', 'Avbryt', 'sv'),
	('common.button.clear', 'አጽዳ', 'am'),
	('common.button.clear', 'مسح', 'ar'),
	('common.button.clear', 'Clear', 'en'),
	('common.button.clear', 'Tyhjennä', 'fi'),
	('common.button.clear', 'Rensa', 'sv'),
	('common.button.close', 'ዝጋ', 'am'),
	('common.button.close', 'إغلاق', 'ar'),
	('common.button.close', 'Close', 'en'),
	('common.button.close', 'Sulje', 'fi'),
	('common.button.close', 'Stäng', 'sv'),
	('common.button.create', 'ፍጠር', 'am'),
	('common.button.create', 'إنشاء', 'ar'),
	('common.button.create', 'Create', 'en'),
	('common.button.create', 'Luo', 'fi'),
	('common.button.create', 'Skapa', 'sv'),
	('common.button.delete', 'ሰርዝ', 'am'),
	('common.button.delete', 'حذف', 'ar'),
	('common.button.delete', 'Delete', 'en'),
	('common.button.delete', 'Poista', 'fi'),
	('common.button.delete', 'Radera', 'sv'),
	('common.button.edit', 'አርትዕ', 'am'),
	('common.button.edit', 'تعديل', 'ar'),
	('common.button.edit', 'Edit', 'en'),
	('common.button.edit', 'Muokkaa', 'fi'),
	('common.button.edit', 'Redigera', 'sv'),
	('common.button.retry', 'እንደገና ሞክር', 'am'),
	('common.button.retry', 'إعادة المحاولة', 'ar'),
	('common.button.retry', 'Retry', 'en'),
	('common.button.retry', 'Yritä uudelleen', 'fi'),
	('common.button.retry', 'Försök igen', 'sv'),
	('common.button.save', 'አስቀምጥ', 'am'),
	('common.button.save', 'حفظ', 'ar'),
	('common.button.save', 'Save', 'en'),
	('common.button.save', 'Tallenna', 'fi'),
	('common.button.save', '', 'ne'),
	('common.button.save', 'Spara', 'sv'),
	('common.button.search', 'ፈልግ', 'am'),
	('common.button.search', 'بحث', 'ar'),
	('common.button.search', 'Search', 'en'),
	('common.button.search', 'Etsi', 'fi'),
	('common.button.search', 'Sök', 'sv'),
	('common.button.update', 'አዘምን', 'am'),
	('common.button.update', 'تحديث', 'ar'),
	('common.button.update', 'Update', 'en'),
	('common.button.update', 'Päivitä', 'fi'),
	('common.button.update', 'Uppdatera', 'sv'),
	('common.confirm.delete', 'ይህን ነገር ለመሰረዝ እርግጠኛ ነዎት?', 'am'),
	('common.confirm.delete', 'هل أنت متأكد من حذف هذا العنصر؟', 'ar'),
	('common.confirm.delete', 'Are you sure you want to delete this item?', 'en'),
	('common.confirm.delete', 'Haluatko varmasti poistaa tämän kohteen?', 'fi'),
	('common.confirm.delete', 'Är du säker på att du vill radera detta objekt?', 'sv'),
	('common.date.format', 'yyyy-MM-dd', 'am'),
	('common.date.format', 'yyyy-MM-dd', 'ar'),
	('common.date.format', 'dd/MM/yyyy', 'en'),
	('common.date.format', 'dd.MM.yyyy', 'fi'),
	('common.date.format', 'yyyy-MM-dd', 'sv'),
	('common.error.forbidden', 'መዳረሻ ተከልክሏል።', 'am'),
	('common.error.forbidden', 'تم حظر الوصول.', 'ar'),
	('common.error.forbidden', 'Access denied.', 'en'),
	('common.error.forbidden', 'Pääsy kielletty.', 'fi'),
	('common.error.forbidden', 'Åtkomst nekad.', 'sv'),
	('common.error.network', 'የአውታረ መረብ ችግኝ። እንደገና ይሞክሩ።', 'am'),
	('common.error.network', 'خطأ في الشبكة. يرجى المحاولة مرة أخرى.', 'ar'),
	('common.error.network', 'Network error. Please try again.', 'en'),
	('common.error.network', 'Nätverksfel. Försök igen.', 'sv'),
	('common.error.notFound', 'ምንም ሀብት አልተገኘም።', 'am'),
	('common.error.notFound', 'العنصر غير موجود.', 'ar'),
	('common.error.notFound', 'Requested resource was not found.', 'en'),
	('common.error.notFound', 'Pyydettyä resurssia ei löytynyt.', 'fi'),
	('common.error.notFound', 'Resursen kunde inte hittas.', 'sv'),
	('common.error.server', 'የአገልጋይ ችግኝ። በኋላ ይሞክሩ።', 'am'),
	('common.error.server', 'خطأ في الخادم. حاول لاحقاً.', 'ar'),
	('common.error.server', 'Server error. Please try again later.', 'en'),
	('common.error.server', 'Palvelinvirhe. Yritä myöhemmin.', 'fi'),
	('common.error.server', 'Serverfel. Försök igen senare.', 'sv'),
	('common.error.unauthorized', 'ይህን ተግባር ለመፈጸም ፍቃድ የሎትም።', 'am'),
	('common.error.unauthorized', 'ليست لديك صلاحية لتنفيذ هذا الإجراء.', 'ar'),
	('common.error.unauthorized', 'You are not authorized to perform this action.', 'en'),
	('common.error.unauthorized', 'Sinulla ei ole lupaa suorittaa tätä toimintoa.', 'fi'),
	('common.error.unauthorized', 'Du har inte behörighet att utföra denna åtgärd.', 'sv'),
	('common.export', 'ላክ', 'am'),
	('common.export', 'تصدير', 'ar'),
	('common.export', 'Export', 'en'),
	('common.export', 'Vie', 'fi'),
	('common.export', 'Exportera', 'sv'),
	('common.export.csv', 'ወደ CSV ላክ', 'am'),
	('common.export.csv', 'تصدير إلى CSV', 'ar'),
	('common.export.csv', 'Export as CSV', 'en'),
	('common.export.csv', 'Vie CSV:nä', 'fi'),
	('common.export.csv', 'Exportera som CSV', 'sv'),
	('common.export.failure', 'መላክ አልተሳካም: {error}', 'am'),
	('common.export.failure', 'فشل التصدير: {error}', 'ar'),
	('common.export.failure', 'Export failed: {error}', 'en'),
	('common.export.failure', 'Vienti epäonnistui: {error}', 'fi'),
	('common.export.failure', 'Export misslyckades: {error}', 'sv'),
	('common.export.pdf', 'ወደ PDF ላክ', 'am'),
	('common.export.pdf', 'تصدير إلى PDF', 'ar'),
	('common.export.pdf', 'Export as PDF', 'en'),
	('common.export.pdf', 'Vie PDF:nä', 'fi'),
	('common.export.pdf', 'Exportera som PDF', 'sv'),
	('common.export.success', 'ሪፖርቱ ወደ {path} ተቀምጧል', 'am'),
	('common.export.success', 'تم حفظ التقرير في {path}', 'ar'),
	('common.export.success', 'Report saved successfully at {path}', 'en'),
	('common.export.success', 'Raportti tallennettu {path}', 'fi'),
	('common.export.success', 'Rapport sparad till {path}', 'sv'),
	('common.number.format', '1,200.30', 'am'),
	('common.number.format', '1,200.30', 'ar'),
	('common.number.format', '1200.3', 'en'),
	('common.number.format', '1 200,30', 'fi'),
	('common.number.format', '1 200,30', 'sv'),
	('common.pagination.next', 'ቀጣይ', 'am'),
	('common.pagination.next', 'التالي', 'ar'),
	('common.pagination.next', 'Next', 'en'),
	('common.pagination.next', 'Seuraava', 'fi'),
	('common.pagination.next', 'Nästa', 'sv'),
	('common.pagination.page', 'ገጽ', 'am'),
	('common.pagination.page', 'صفحة', 'ar'),
	('common.pagination.page', 'Page', 'en'),
	('common.pagination.page', 'Sivu', 'fi'),
	('common.pagination.page', 'Sida', 'sv'),
	('common.pagination.previous', 'ያለፈው', 'am'),
	('common.pagination.previous', 'السابق', 'ar'),
	('common.pagination.previous', 'Previous', 'en'),
	('common.pagination.previous', 'Edellinen', 'fi'),
	('common.pagination.previous', 'Föregående', 'sv'),
	('common.status.failed', 'አልተሳካም', 'am'),
	('common.status.failed', 'فشل التنفيذ', 'ar'),
	('common.status.failed', 'Failed', 'en'),
	('common.status.failed', 'Epäonnistui', 'fi'),
	('common.status.failed', 'Misslyckades', 'sv'),
	('common.status.loading', 'በመጫን ላይ...', 'am'),
	('common.status.loading', 'جارٍ التحميل...', 'ar'),
	('common.status.loading', 'Loading...', 'en'),
	('common.status.loading', 'Ladataan..', 'fi'),
	('common.status.loading', 'Laddar...', 'sv'),
	('common.status.noData', 'ምንም መረጃ የለም', 'am'),
	('common.status.noData', 'لا توجد بيانات', 'ar'),
	('common.status.noData', 'No data available', 'en'),
	('common.status.noData', 'Ei tietoja saatavilla', 'fi'),
	('common.status.noData', 'Inga data tillgängliga', 'sv'),
	('common.status.success', 'ተሳክቷል', 'am'),
	('common.status.success', 'تم بنجاح', 'ar'),
	('common.status.success', 'Success', 'en'),
	('common.status.success', 'Onnistui', 'fi'),
	('common.status.success', 'Lyckades', 'sv'),
	('common.table.column.absentCount', 'አልተገኘም', 'am'),
	('common.table.column.absentCount', 'غائب', 'ar'),
	('common.table.column.absentCount', 'Absent', 'en'),
	('common.table.column.absentCount', 'Poissa', 'fi'),
	('common.table.column.absentCount', 'Frånvarande', 'sv'),
	('common.table.column.attendanceRate', 'የመገኘት መጠን', 'am'),
	('common.table.column.attendanceRate', 'نسبة الحضور', 'ar'),
	('common.table.column.attendanceRate', 'Läsnäoloprosentti', 'fi'),
	('common.table.column.attendanceRate', 'Närvaroprocent', 'sv'),
	('common.table.column.class', 'ክፍል', 'am'),
	('common.table.column.class', 'الفصل', 'ar'),
	('common.table.column.class', 'Luokka', 'fi'),
	('common.table.column.class', 'Klass', 'sv'),
	('common.table.column.date', 'ቀን', 'am'),
	('common.table.column.date', 'التاريخ', 'ar'),
	('common.table.column.date', 'Päivämäärä', 'fi'),
	('common.table.column.date', 'Datum', 'sv'),
	('common.table.column.email', 'ኢሜይል', 'am'),
	('common.table.column.email', 'البريد الإلكتروني', 'ar'),
	('common.table.column.email', 'Sähköposti', 'fi'),
	('common.table.column.email', 'E‑post', 'sv'),
	('common.table.column.id', 'መለያ', 'am'),
	('common.table.column.id', 'المعرف', 'ar'),
	('common.table.column.id', 'ID', 'fi'),
	('common.table.column.id', 'ID', 'sv'),
	('common.table.column.name', 'ስም', 'am'),
	('common.table.column.name', 'الاسم', 'ar'),
	('common.table.column.name', 'Nimi', 'fi'),
	('common.table.column.name', 'Namn', 'sv'),
	('common.table.column.presentCount', 'ተገኝቷል', 'am'),
	('common.table.column.presentCount', 'حاضر', 'ar'),
	('common.table.column.presentCount', 'Läsnä', 'fi'),
	('common.table.column.presentCount', 'Närvarande', 'sv'),
	('common.table.column.role', 'ሚና', 'am'),
	('common.table.column.role', 'الدور', 'ar'),
	('common.table.column.role', 'Rooli', 'fi'),
	('common.table.column.role', 'Roll', 'sv'),
	('common.table.column.session', 'ክፍለ ጊዜ', 'am'),
	('common.table.column.session', 'الجلسة', 'ar'),
	('common.table.column.session', 'Istunto', 'fi'),
	('common.table.column.session', 'Session', 'sv'),
	('common.table.column.status', 'ሁኔታ', 'am'),
	('common.table.column.status', 'الحالة', 'ar'),
	('common.table.column.status', 'Tila', 'fi'),
	('common.table.column.status', 'Status', 'sv'),
	('common.table.empty', 'ምንም መረጃ የለም', 'am'),
	('common.table.empty', 'لا توجد بيانات', 'ar'),
	('common.table.empty', 'No records to display', 'en'),
	('common.table.empty', 'Ei tietueita', 'fi'),
	('common.table.empty', 'Inga poster', 'sv'),
	('common.table.emptyMessage', 'በሰንጠረዡ ውስጥ መረጃ የለም', 'am'),
	('common.table.emptyMessage', 'لا توجد بيانات في الجدول', 'ar'),
	('common.table.emptyMessage', 'No data available in table', 'en'),
	('common.table.emptyMessage', 'Taulukossa ei ole tietoja', 'fi'),
	('common.table.emptyMessage', 'Tabellen innehåller inga data', 'sv'),
	('common.table.of', '/', 'am'),
	('common.table.of', 'من', 'ar'),
	('common.table.of', '/', 'fi'),
	('common.table.of', '/', 'sv'),
	('common.table.rowsPerPage', 'በገጽ ላይ የሚታዩ ረድፎች', 'am'),
	('common.table.rowsPerPage', 'عدد الصفوف في الصفحة', 'ar'),
	('common.table.rowsPerPage', 'Rows per page', 'en'),
	('common.table.rowsPerPage', 'Riviä sivulla', 'fi'),
	('common.table.rowsPerPage', 'Rader per sida', 'sv'),
	('common.time.format', 'HH:mm', 'am'),
	('common.time.format', 'HH:mm', 'ar'),
	('common.time.format', 'HH:mm', 'en'),
	('common.time.format', 'HH.mm', 'fi'),
	('common.time.format', 'HH:mm', 'sv'),
	('common.validation.invalidDateRange', 'የመጀመሪያ ቀን ከመጨረሻ ቀን በፊት መሆን አለበት።', 'am'),
	('common.validation.invalidDateRange', 'يجب أن يكون تاريخ البدء قبل تاريخ الانتهاء.', 'ar'),
	('common.validation.invalidDateRange', 'Start date must be before end date.', 'en'),
	('common.validation.invalidDateRange', 'Aloituspäivän on oltava ennen päättymispäivää.', 'fi'),
	('common.validation.invalidDateRange', 'Startdatum måste vara före slutdatum.', 'sv'),
	('common.validation.invalidEmail', 'ትክክለኛ የኢሜይል አድራሻ ያስገቡ።', 'am'),
	('common.validation.invalidEmail', 'يرجى إدخال بريد إلكتروني صالح.', 'ar'),
	('common.validation.invalidEmail', 'Please enter a valid email address.', 'en'),
	('common.validation.invalidEmail', 'Syötä kelvollinen sähköpostiosoite.', 'fi'),
	('common.validation.invalidEmail', 'Ange en giltig e‑postadress.', 'sv'),
	('common.validation.required', 'ይህ መስክ አስፈላጊ ነው።', 'am'),
	('common.validation.required', 'هذا الحقل مطلوب.', 'ar'),
	('common.validation.required', 'This field is required.', 'en'),
	('common.validation.required', 'Tämä kenttä on pakollinen.', 'fi'),
	('common.validation.required', 'Detta fält är obligatoriskt.', 'sv'),
	('login.button.signup', 'መለያ የለኝም', 'am'),
	('login.button.signup', 'ليس لدي حساب', 'ar'),
	('login.button.signup', 'I don\'t have an account', 'en'),
	('login.button.signup', 'Minulla ei ole tiliä', 'fi'),
	('login.button.signup', 'Jag har inget konto', 'sv'),
	('login.button.submit', 'ግባ', 'am'),
	('login.button.submit', 'تسجيل الدخول', 'ar'),
	('login.button.submit', 'Log in', 'en'),
	('login.button.submit', 'Kirjaudu', 'fi'),
	('login.button.submit', 'Logga in', 'sv'),
	('login.email.placeholder', 'ኢሜይል', 'am'),
	('login.email.placeholder', 'البريد الإلكتروني', 'ar'),
	('login.email.placeholder', 'Email', 'en'),
	('login.email.placeholder', 'Sähköposti', 'fi'),
	('login.email.placeholder', 'E‑post', 'sv'),
	('login.error.empty_fields', 'ኢሜይልና የይለፍ ቃል ይሙሉ።', 'am'),
	('login.error.empty_fields', 'يرجى ملء البريد الإلكتروني وكلمة المرور.', 'ar'),
	('login.error.empty_fields', 'Please enter email and password.', 'en'),
	('login.error.empty_fields', 'Syötä sähköposti ja salasana.', 'fi'),
	('login.error.empty_fields', 'Fyll i både e‑post och lösenord.', 'sv'),
	('login.error.failed', 'መግባት አልተሳካም:', 'am'),
	('login.error.failed', 'فشل تسجيل الدخول:', 'ar'),
	('login.error.failed', 'Login failed:', 'en'),
	('login.error.failed', 'Kirjautuminen epäonnistui:', 'fi'),
	('login.error.failed', 'Inloggning misslyckades:', 'sv'),
	('login.error.unknown', 'ያልታወቀ ችግኝ', 'am'),
	('login.error.unknown', 'خطأ غير معروف', 'ar'),
	('login.error.unknown', 'Unknown error', 'en'),
	('login.error.unknown', 'Tuntematon virhe', 'fi'),
	('login.error.unknown', 'Okänt fel', 'sv'),
	('login.password.placeholder', 'የይለፍ ቃል', 'am'),
	('login.password.placeholder', 'كلمة المرور', 'ar'),
	('login.password.placeholder', 'Password', 'en'),
	('login.password.placeholder', 'Salasana', 'fi'),
	('login.password.placeholder', 'Lösenord', 'sv'),
	('signup.button.login', 'መለያ አለኝ', 'am'),
	('signup.button.login', 'لدي حساب بالفعل', 'ar'),
	('signup.button.login', 'I already have an account', 'en'),
	('signup.button.login', 'Minulla on jo tili', 'fi'),
	('signup.button.login', 'Jag har redan ett konto', 'sv'),
	('signup.button.submit', 'ይመዝገቡ', 'am'),
	('signup.button.submit', 'إنشاء حساب', 'ar'),
	('signup.button.submit', 'Sign up', 'en'),
	('signup.button.submit', 'Rekisteröidy', 'fi'),
	('signup.button.submit', 'Registrera', 'sv'),
	('signup.email.label', 'ኢሜይል', 'am'),
	('signup.email.label', 'البريد الإلكتروني', 'ar'),
	('signup.email.label', 'Email', 'en'),
	('signup.email.label', 'Sähköposti', 'fi'),
	('signup.email.label', 'E‑post', 'sv'),
	('signup.email.placeholder', 'ኢሜይል', 'am'),
	('signup.email.placeholder', 'البريد الإلكتروني', 'ar'),
	('signup.email.placeholder', 'Email', 'en'),
	('signup.email.placeholder', 'Sähköposti', 'fi'),
	('signup.email.placeholder', 'E‑post', 'sv'),
	('signup.error.failed', 'መመዝገብ አልተሳካም:', 'am'),
	('signup.error.failed', 'فشل إنشاء الحساب:', 'ar'),
	('signup.error.failed', 'Signup failed:', 'en'),
	('signup.error.failed', 'Rekisteröinti epäonnistui:', 'fi'),
	('signup.error.failed', 'Registrering misslyckades:', 'sv'),
	('signup.error.invalid_email', 'ትክክለኛ የኢሜይል አድራሻ ያስገቡ።', 'am'),
	('signup.error.invalid_email', 'يرجى إدخال بريد إلكتروني صالح.', 'ar'),
	('signup.error.invalid_email', 'Please enter a valid email.', 'en'),
	('signup.error.invalid_email', 'Syötä kelvollinen sähköposti.', 'fi'),
	('signup.error.invalid_email', 'Ange en giltig e‑postadress.', 'sv'),
	('signup.error.password_short', 'የይለፍ ቃሉ ቢያንስ 6 ቁምፊ መሆን አለበት።', 'am'),
	('signup.error.password_short', 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.', 'ar'),
	('signup.error.password_short', 'Password must be at least 6 characters.', 'en'),
	('signup.error.password_short', 'Salasanan on oltava vähintään 6 merkkiä.', 'fi'),
	('signup.error.password_short', 'Lösenordet måste vara minst 6 tecken.', 'sv'),
	('signup.error.required_fields', 'ሁሉንም አስፈላጊ መስኮች ይሙሉ።', 'am'),
	('signup.error.required_fields', 'يرجى ملء جميع الحقول المطلوبة.', 'ar'),
	('signup.error.required_fields', 'Please fill in all required fields.', 'en'),
	('signup.error.required_fields', 'Täytä kaikki pakolliset kentät.', 'fi'),
	('signup.error.required_fields', 'Fyll i alla obligatoriska fält.', 'sv'),
	('signup.error.student_code_required', 'ለተማሪዎች የተማሪ ኮድ ያስፈልጋል።', 'am'),
	('signup.error.student_code_required', 'رمز الطالب مطلوب للطلاب.', 'ar'),
	('signup.error.student_code_required', 'Student code is required for students.', 'en'),
	('signup.error.student_code_required', 'Opiskelijatunnus vaaditaan opiskelijoille.', 'fi'),
	('signup.error.student_code_required', 'Studentkod krävs för studenter.', 'sv'),
	('signup.firstname.label', 'ስም', 'am'),
	('signup.firstname.label', 'الاسم الأول', 'ar'),
	('signup.firstname.label', 'First name', 'en'),
	('signup.firstname.label', 'Etunimi', 'fi'),
	('signup.firstname.label', 'Förnamn', 'sv'),
	('signup.firstname.placeholder', 'ስም', 'am'),
	('signup.firstname.placeholder', 'الاسم الأول', 'ar'),
	('signup.firstname.placeholder', 'First name', 'en'),
	('signup.firstname.placeholder', 'Etunimi', 'fi'),
	('signup.firstname.placeholder', 'Förnamn', 'sv'),
	('signup.lastname.label', 'የአባት ስም', 'am'),
	('signup.lastname.label', 'اسم العائلة', 'ar'),
	('signup.lastname.label', 'Last name', 'en'),
	('signup.lastname.label', 'Sukunimi', 'fi'),
	('signup.lastname.label', 'Efternamn', 'sv'),
	('signup.lastname.placeholder', 'የአባት ስም', 'am'),
	('signup.lastname.placeholder', 'اسم العائلة', 'ar'),
	('signup.lastname.placeholder', 'Last name', 'en'),
	('signup.lastname.placeholder', 'Sukunimi', 'fi'),
	('signup.lastname.placeholder', 'Efternamn', 'sv'),
	('signup.password.label', 'የይለፍ ቃል', 'am'),
	('signup.password.label', 'كلمة المرور', 'ar'),
	('signup.password.label', 'Password', 'en'),
	('signup.password.label', 'Salasana', 'fi'),
	('signup.password.label', 'Lösenord', 'sv'),
	('signup.password.placeholder', 'የይለፍ ቃል', 'am'),
	('signup.password.placeholder', 'Password', 'en'),
	('signup.password.placeholder', 'Salasana', 'fi'),
	('signup.password.placeholder', 'Lösenord', 'sv'),
	('signup.role.label', 'ሚና', 'am'),
	('signup.role.label', 'الدور', 'ar'),
	('signup.role.label', 'Role', 'en'),
	('signup.role.label', 'Rooli', 'fi'),
	('signup.role.label', 'Roll', 'sv'),
	('signup.role.student', 'ተማሪ', 'am'),
	('signup.role.student', 'طالب', 'ar'),
	('signup.role.student', 'Student', 'en'),
	('signup.role.student', 'Opiskelija', 'fi'),
	('signup.role.student', 'Student', 'sv'),
	('signup.role.teacher', 'አስተማሪ', 'am'),
	('signup.role.teacher', 'معلم', 'ar'),
	('signup.role.teacher', 'Teacher', 'en'),
	('signup.role.teacher', 'Opettaja', 'fi'),
	('signup.role.teacher', 'Lärare', 'sv'),
	('signup.studentcode.label', 'የተማሪ ኮድ', 'am'),
	('signup.studentcode.label', 'رمز الطالب', 'ar'),
	('signup.studentcode.label', 'Student code', 'en'),
	('signup.studentcode.label', 'Opiskelijatunnus', 'fi'),
	('signup.studentcode.label', 'Studentkod', 'sv'),
	('signup.studentcode.placeholder', 'ለምሳሌ 123456', 'am'),
	('signup.studentcode.placeholder', 'مثال: 123456', 'ar'),
	('signup.studentcode.placeholder', 'e.g. 123456', 'en'),
	('signup.studentcode.placeholder', 'esim. 123456', 'fi'),
	('signup.studentcode.placeholder', 't.ex. 123456', 'sv'),
	('signup.subtitle', 'ስርዓቱን ለመጠቀም ይመዝገቡ', 'am'),
	('signup.subtitle', 'سجّل لإنشاء حساب جديد', 'ar'),
	('signup.subtitle', 'Sign up to start using the system', 'en'),
	('signup.subtitle', 'Rekisteröidy käyttääksesi järjestelmää', 'fi'),
	('signup.subtitle', 'Registrera dig för att använda systemet', 'sv'),
	('signup.success.created', 'መለያ ተፈጥሯል። ይግቡ።', 'am'),
	('signup.success.created', 'تم إنشاء الحساب بنجاح. يرجى تسجيل الدخول.', 'ar'),
	('signup.success.created', 'Account created. Please login.', 'en'),
	('signup.success.created', 'Tili luotu. Kirjaudu sisään.', 'fi'),
	('signup.success.created', 'Konto skapat. Logga in.', 'sv'),
	('signup.title', 'መለያ ፍጠር', 'am'),
	('signup.title', 'إنشاء حساب', 'ar'),
	('signup.title', 'Create account', 'en'),
	('signup.title', 'Luo tili', 'fi'),
	('signup.title', 'Skapa konto', 'sv'),
	('student.dashboard.markAttendance.subtitle', 'ለመመዝገብ QR ኮድ ይስካኑ', 'am'),
	('student.dashboard.markAttendance.subtitle', 'امسح رمز QR للتسجيل', 'ar'),
	('student.dashboard.markAttendance.subtitle', 'Scan the QR code to check in', 'en'),
	('student.dashboard.markAttendance.subtitle', 'Skannaa QR-koodi kirjautuaksesi sisään', 'fi'),
	('student.dashboard.markAttendance.subtitle', 'Skanna QR‑koden för att checka in', 'sv'),
	('student.dashboard.markAttendance.title', 'መገኘት ይመዝግቡ', 'am'),
	('student.dashboard.markAttendance.title', 'تسجيل الحضور', 'ar'),
	('student.dashboard.markAttendance.title', 'Mark Attendance', 'en'),
	('student.dashboard.markAttendance.title', 'Merkitse läsnäolo', 'fi'),
	('student.dashboard.markAttendance.title', 'Registrera närvaro', 'sv'),
	('student.dashboard.subtitle', 'የወሩ የመገኘት ማጠቃለያዎ እዚህ ነው', 'am'),
	('student.dashboard.subtitle', 'ملخص حضورك الشهري يظهر هنا', 'ar'),
	('student.dashboard.subtitle', 'Here’s your attendance overview for this month', 'en'),
	('student.dashboard.subtitle', 'Tässä on tämän kuun läsnäoloyhteenveto', 'fi'),
	('student.dashboard.subtitle', 'Här är månadens närvarosammanfattning', 'sv'),
	('student.dashboard.title', 'እንኳን በደህና መጡ {name}!', 'am'),
	('student.dashboard.title', 'مرحباً بك {name}!', 'ar'),
	('student.dashboard.title', 'Welcome back, {name}!', 'en'),
	('student.dashboard.title', 'Tervetuloa takaisin, {name}!', 'fi'),
	('student.dashboard.title', 'Välkommen tillbaka, {name}!', 'sv'),
	('teacher.attendance.alert.generateSession', 'መጀመሪያ ሴሽን ይፍጠሩ።', 'am'),
	('teacher.attendance.alert.generateSession', 'يرجى إنشاء جلسة أولاً.', 'ar'),
	('teacher.attendance.alert.generateSession', 'Please generate a session first.', 'en'),
	('teacher.attendance.alert.generateSession', 'Luo ensin istunto.', 'fi'),
	('teacher.attendance.alert.generateSession', 'Skapa en session först.', 'sv'),
	('teacher.attendance.alert.selectClass', 'መጀመሪያ ክፍል ይምረጡ።', 'am'),
	('teacher.attendance.alert.selectClass', 'يرجى اختيار الفصل أولاً.', 'ar'),
	('teacher.attendance.alert.selectClass', 'Please select a class first.', 'en'),
	('teacher.attendance.alert.selectClass', 'Valitse ensin luokka.', 'fi'),
	('teacher.attendance.alert.selectClass', 'Välj en klass först.', 'sv'),
	('teacher.attendance.class.prompt', 'ክፍል ይምረጡ', 'am'),
	('teacher.attendance.class.prompt', 'اختر الفصل', 'ar'),
	('teacher.attendance.class.prompt', 'Choose a class', 'en'),
	('teacher.attendance.class.prompt', 'Valitse luokka', 'fi'),
	('teacher.attendance.class.prompt', 'Välj klass', 'sv'),
	('teacher.attendance.error.generate', 'ሴሽን መፍጠር አልተሳካም:', 'am'),
	('teacher.attendance.error.generate', 'فشل إنشاء الجلسة:', 'ar'),
	('teacher.attendance.error.generate', 'Generate failed:', 'en'),
	('teacher.attendance.error.generate', 'Luonti epäonnistui:', 'fi'),
	('teacher.attendance.error.generate', 'Skapande misslyckades:', 'sv'),
	('teacher.attendance.error.loadClasses', 'ክፍሎችን መጫን አልተቻለም:', 'am'),
	('teacher.attendance.error.loadClasses', 'تعذر تحميل الفصول:', 'ar'),
	('teacher.attendance.error.loadClasses', 'Luokkien lataus epäonnistui:', 'fi'),
	('teacher.attendance.error.loadClasses', 'Kunde inte ladda klasser:', 'sv'),
	('teacher.attendance.error.loadStudents', 'ተማሪዎችን መጫን አልተቻለም:', 'am'),
	('teacher.attendance.error.loadStudents', 'تعذر تحميل الطلاب:', 'ar'),
	('teacher.attendance.error.loadStudents', 'Opiskelijoiden lataus epäonnistui:', 'fi'),
	('teacher.attendance.error.loadStudents', 'Kunde inte ladda studenter:', 'sv'),
	('teacher.attendance.error.markAll', 'ሁሉንም ማምለክት አልተሳካም:', 'am'),
	('teacher.attendance.error.markAll', 'فشل تحديد الجميع كحاضر:', 'ar'),
	('teacher.attendance.error.markAll', 'Kaikkien merkitseminen epäonnistui:', 'fi'),
	('teacher.attendance.error.markAll', 'Kunde inte markera alla:', 'sv'),
	('teacher.attendance.error.update', 'የመገኘት ሁኔታ ማዘመን አልተሳካም:', 'am'),
	('teacher.attendance.error.update', 'فشل تحديث حالة الحضور:', 'ar'),
	('teacher.attendance.error.update', 'Failed to update attendance:', 'en'),
	('teacher.attendance.error.update', 'Läsnäolon päivitys epäonnistui:', 'fi'),
	('teacher.attendance.error.update', 'Uppdatering av närvaro misslyckades:', 'sv'),
	('teacher.attendance.generate', 'ኮድ ይፍጠሩ', 'am'),
	('teacher.attendance.generate', 'إنشاء الرمز', 'ar'),
	('teacher.attendance.generate', 'Generate Code', 'en'),
	('teacher.attendance.generate', 'Luo koodi', 'fi'),
	('teacher.attendance.generate', 'Skapa kod', 'sv'),
	('teacher.attendance.generating', 'በመፍጠር ላይ...', 'am'),
	('teacher.attendance.generating', 'جارٍ الإنشاء...', 'ar'),
	('teacher.attendance.generating', 'Generating...', 'en'),
	('teacher.attendance.generating', 'Luodaan...', 'fi'),
	('teacher.attendance.generating', 'Skapar...', 'sv'),
	('teacher.attendance.loading.students', 'በመጫን ላይ...', 'am'),
	('teacher.attendance.loading.students', 'جارٍ تحميل الطلاب...', 'ar'),
	('teacher.attendance.loading.students', 'Loading...', 'en'),
	('teacher.attendance.loading.students', 'Ladataan...', 'fi'),
	('teacher.attendance.loading.students', 'Laddar...', 'sv'),
	('teacher.attendance.manual.title', 'በእጅ ኮድ', 'am'),
	('teacher.attendance.manual.title', 'رمز يدوي', 'ar'),
	('teacher.attendance.manual.title', 'Manual Code', 'en'),
	('teacher.attendance.manual.title', 'Manuaalinen koodi', 'fi'),
	('teacher.attendance.manual.title', 'Manuell kod', 'sv'),
	('teacher.attendance.markAll', 'ሁሉንም እንደተገኙ ምልክት ያድርጉ', 'am'),
	('teacher.attendance.markAll', 'تحديد الجميع كحاضر', 'ar'),
	('teacher.attendance.markAll', 'Mark All Present', 'en'),
	('teacher.attendance.markAll', 'Merkitse kaikki läsnä', 'fi'),
	('teacher.attendance.markAll', 'Markera alla som närvarande', 'sv'),
	('teacher.attendance.qr.title', 'የመገኘት QR ኮድ', 'am'),
	('teacher.attendance.qr.title', 'رمز QR للحضور', 'ar'),
	('teacher.attendance.qr.title', 'Attendance QR Code', 'en'),
	('teacher.attendance.qr.title', 'Läsnäolon QR-koodi', 'fi'),
	('teacher.attendance.qr.title', 'QR‑kod för närvaro', 'sv'),
	('teacher.attendance.selectClass', 'ክፍል ይምረጡ', 'am'),
	('teacher.attendance.selectClass', 'اختر الفصل', 'ar'),
	('teacher.attendance.selectClass', 'Select class', 'en'),
	('teacher.attendance.selectClass', 'Valitse luokka', 'fi'),
	('teacher.attendance.selectClass', 'Välj klass', 'sv'),
	('teacher.attendance.status.absent', 'አልተገኘም', 'am'),
	('teacher.attendance.status.absent', 'غائب', 'ar'),
	('teacher.attendance.status.absent', 'ABSENT', 'en'),
	('teacher.attendance.status.absent', 'POISSA', 'fi'),
	('teacher.attendance.status.absent', 'FRÅNVARANDE', 'sv'),
	('teacher.attendance.status.excused', 'ተሰርዟል', 'am'),
	('teacher.attendance.status.excused', 'معذور', 'ar'),
	('teacher.attendance.status.excused', 'EXCUSED', 'en'),
	('teacher.attendance.status.excused', 'VAPAUTETTU', 'fi'),
	('teacher.attendance.status.excused', 'URSÄKTAD', 'sv'),
	('teacher.attendance.status.present', 'ተገኝቷል', 'am'),
	('teacher.attendance.status.present', 'حاضر', 'ar'),
	('teacher.attendance.status.present', 'PRESENT', 'en'),
	('teacher.attendance.status.present', 'LÄSNÄ', 'fi'),
	('teacher.attendance.status.present', 'NÄRVARANDE', 'sv'),
	('teacher.attendance.students.title', 'ተማሪዎች ({count})', 'am'),
	('teacher.attendance.students.title', 'الطلاب ({count})', 'ar'),
	('teacher.attendance.students.title', 'Students ({count})', 'en'),
	('teacher.attendance.students.title', 'Opiskelijat ({count})', 'fi'),
	('teacher.attendance.students.title', 'Studenter ({count})', 'sv'),
	('teacher.attendance.subtitle', 'ክፍል ይምረጡ እና QR ኮድ ይፍጠሩ', 'am'),
	('teacher.attendance.subtitle', 'اختر فصلاً وأنشئ رمز QR', 'ar'),
	('teacher.attendance.subtitle', 'Select class and generate QR code', 'en'),
	('teacher.attendance.subtitle', 'Valitse luokka ja luo QR-koodi', 'fi'),
	('teacher.attendance.subtitle', 'Välj klass och skapa QR‑kod', 'sv'),
	('teacher.attendance.table.actions', 'ተግባሮች', 'am'),
	('teacher.attendance.table.actions', 'الإجراءات', 'ar'),
	('teacher.attendance.table.actions', 'Actions', 'en'),
	('teacher.attendance.table.actions', 'Toiminnot', 'fi'),
	('teacher.attendance.table.actions', 'Åtgärder', 'sv'),
	('teacher.attendance.table.email', 'ኢሜይል', 'am'),
	('teacher.attendance.table.email', 'البريد الإلكتروني', 'ar'),
	('teacher.attendance.table.email', 'Email', 'en'),
	('teacher.attendance.table.email', 'Sähköposti', 'fi'),
	('teacher.attendance.table.email', 'E‑post', 'sv'),
	('teacher.attendance.table.status', 'ሁኔታ', 'am'),
	('teacher.attendance.table.status', 'الحالة', 'ar'),
	('teacher.attendance.table.status', 'Status', 'en'),
	('teacher.attendance.table.status', 'Tila', 'fi'),
	('teacher.attendance.table.status', 'Status', 'sv'),
	('teacher.attendance.table.student', 'ተማሪ', 'am'),
	('teacher.attendance.table.student', 'الطالب', 'ar'),
	('teacher.attendance.table.student', 'Student', 'en'),
	('teacher.attendance.table.student', 'Opiskelija', 'fi'),
	('teacher.attendance.table.student', 'Student', 'sv'),
	('teacher.attendance.title', 'መገኘት ይመዝግቡ', 'am'),
	('teacher.attendance.title', 'تسجيل الحضور', 'ar'),
	('teacher.attendance.title', 'Take Attendance', 'en'),
	('teacher.attendance.title', 'Merkitse läsnäolo', 'fi'),
	('teacher.attendance.title', 'Registrera närvaro', 'sv'),
	('teacher.dashboard.classes.empty.subtitle', 'እስካሁን ምንም ክፍል አልተመደበልዎትም።', 'am'),
	('teacher.dashboard.classes.empty.subtitle', 'لم يتم تعيين أي فصل لك حتى الآن.', 'ar'),
	('teacher.dashboard.classes.empty.subtitle', 'You haven’t been assigned any classes yet.', 'en'),
	('teacher.dashboard.classes.empty.subtitle', 'Sinulle ei ole vielä määritetty luokkia.', 'fi'),
	('teacher.dashboard.classes.empty.subtitle', 'Du har ännu inte tilldelats några klasser.', 'sv'),
	('teacher.dashboard.classes.empty.title', 'ክፍሎች የሉም', 'am'),
	('teacher.dashboard.classes.empty.title', 'لا توجد فصول', 'ar'),
	('teacher.dashboard.classes.empty.title', 'No classes Assigned', 'en'),
	('teacher.dashboard.classes.empty.title', 'Ei luokkia', 'fi'),
	('teacher.dashboard.classes.empty.title', 'Inga klasser', 'sv'),
	('teacher.dashboard.classes.loading', 'ክፍሎችን በመጫን ላይ...', 'am'),
	('teacher.dashboard.classes.loading', 'جارٍ تحميل الفصول...', 'ar'),
	('teacher.dashboard.classes.loading', 'Loading classes...', 'en'),
	('teacher.dashboard.classes.loading', 'Ladataan luokkia...', 'fi'),
	('teacher.dashboard.classes.loading', 'Laddar klasser...', 'sv'),
	('teacher.dashboard.classes.meta', 'ሴሚስተር: {semester} | ዓመት: {year} | ተማሪዎች: {count}', 'am'),
	('teacher.dashboard.classes.meta', 'الفصل الدراسي: {semester} | السنة: {year} | الطلاب: {count}', 'ar'),
	('teacher.dashboard.classes.meta', 'Semester: {semester} | Year: {year} | Students: {count}', 'en'),
	('teacher.dashboard.classes.meta', 'Lukukausi: {semester} | Vuosi: {year} | Opiskelijoita: {count}', 'fi'),
	('teacher.dashboard.classes.meta', 'Termin: {semester} | År: {year} | Studenter: {count}', 'sv'),
	('teacher.dashboard.classes.title', 'የእኔ ክፍሎች', 'am'),
	('teacher.dashboard.classes.title', 'فصولي', 'ar'),
	('teacher.dashboard.classes.title', 'My classes', 'en'),
	('teacher.dashboard.classes.title', 'Luokkani', 'fi'),
	('teacher.dashboard.classes.title', 'Mina klasser', 'sv'),
	('teacher.dashboard.classes.unnamed', 'ያልተሰየመ ክፍል', 'am'),
	('teacher.dashboard.classes.unnamed', 'فصل بدون اسم', 'ar'),
	('teacher.dashboard.classes.unnamed', 'Unnamed Class', 'en'),
	('teacher.dashboard.classes.unnamed', 'Nimetön luokka', 'fi'),
	('teacher.dashboard.classes.unnamed', 'Namnlös klass', 'sv'),
	('teacher.dashboard.error.classes', 'ክፍሎችን መጫን አልተቻለም: {error}', 'am'),
	('teacher.dashboard.error.classes', 'تعذر تحميل الفصول: {error}', 'ar'),
	('teacher.dashboard.error.classes', 'Failed to load classes: {error}', 'en'),
	('teacher.dashboard.error.classes', 'Luokkien lataus epäonnistui: {error}', 'fi'),
	('teacher.dashboard.error.classes', 'Kunde inte ladda klasser: {error}', 'sv'),
	('teacher.dashboard.error.stats', 'ስታቲስቲክስ መጫን አልተቻለም: {error}', 'am'),
	('teacher.dashboard.error.stats', 'تعذر تحميل الإحصائيات: {error}', 'ar'),
	('teacher.dashboard.error.stats', 'Failed to load dashboard stats: {error}', 'en'),
	('teacher.dashboard.error.stats', 'Tilastojen lataus epäonnistui: {error}', 'fi'),
	('teacher.dashboard.error.stats', 'Kunde inte ladda statistik: {error}', 'sv'),
	('teacher.dashboard.greeting', 'እንደምን አደሩ {name}!', 'am'),
	('teacher.dashboard.greeting', 'مرحباً {name}!', 'ar'),
	('teacher.dashboard.greeting', 'Good afternoon, {name}!', 'en'),
	('teacher.dashboard.greeting', 'Hyvää iltapäivää, {name}!', 'fi'),
	('teacher.dashboard.greeting', 'God eftermiddag, {name}!', 'sv'),
	('teacher.dashboard.quickActions.manageClasses', 'ክፍሎችን ያቀናብሩ', 'am'),
	('teacher.dashboard.quickActions.manageClasses', 'إدارة الفصول', 'ar'),
	('teacher.dashboard.quickActions.manageClasses', 'Manage Classes', 'en'),
	('teacher.dashboard.quickActions.manageClasses', 'Hallinnoi luokkia', 'fi'),
	('teacher.dashboard.quickActions.manageClasses', 'Hantera klasser', 'sv'),
	('teacher.dashboard.quickActions.manageClasses.desc', 'ክፍሎችን ይጨምሩ፣ ያርትዑ ወይም ያስወግዱ', 'am'),
	('teacher.dashboard.quickActions.manageClasses.desc', 'إضافة أو تعديل أو حذف الفصول', 'ar'),
	('teacher.dashboard.quickActions.manageClasses.desc', 'Add, edit or remove classes', 'en'),
	('teacher.dashboard.quickActions.manageClasses.desc', 'Lisää, muokkaa tai poista luokkia', 'fi'),
	('teacher.dashboard.quickActions.manageClasses.desc', 'Lägg till, redigera eller ta bort klasser', 'sv'),
	('teacher.dashboard.quickActions.manageUsers', 'ተጠቃሚዎችን ያቀናብሩ', 'am'),
	('teacher.dashboard.quickActions.manageUsers', 'إدارة المستخدمين', 'ar'),
	('teacher.dashboard.quickActions.manageUsers', 'Manage Users', 'en'),
	('teacher.dashboard.quickActions.manageUsers', 'Hallinnoi käyttäjiä', 'fi'),
	('teacher.dashboard.quickActions.manageUsers', 'Hantera användare', 'sv'),
	('teacher.dashboard.quickActions.manageUsers.desc', 'የተማሪዎች መመዝገብና መረጃ', 'am'),
	('teacher.dashboard.quickActions.manageUsers.desc', 'تسجيل الطلاب وإدارة بياناتهم', 'ar'),
	('teacher.dashboard.quickActions.manageUsers.desc', 'Student registration and details', 'en'),
	('teacher.dashboard.quickActions.manageUsers.desc', 'Opiskelijoiden rekisteröinti ja tiedot', 'fi'),
	('teacher.dashboard.quickActions.manageUsers.desc', 'Registrering och information om studenter', 'sv'),
	('teacher.dashboard.quickActions.reports', 'መገኘት ሪፖርቶች', 'am'),
	('teacher.dashboard.quickActions.reports', 'تقارير الحضور', 'ar'),
	('teacher.dashboard.quickActions.reports', 'Attendance Reports', 'en'),
	('teacher.dashboard.quickActions.reports', 'Läsnäoloraportit', 'fi'),
	('teacher.dashboard.quickActions.reports', 'Närvarorapporter', 'sv'),
	('teacher.dashboard.quickActions.reports.desc', 'ዝርዝር ሪፖርቶችን ይመልከቱ', 'am'),
	('teacher.dashboard.quickActions.reports.desc', 'عرض التقارير التفصيلية', 'ar'),
	('teacher.dashboard.quickActions.reports.desc', 'View comprehensive reports', 'en'),
	('teacher.dashboard.quickActions.reports.desc', 'Näytä kattavat raportit', 'fi'),
	('teacher.dashboard.quickActions.reports.desc', 'Visa detaljerade rapporter', 'sv'),
	('teacher.dashboard.reports.subtitle', 'የክፍል መገኘት ሪፖርቶች', 'am'),
	('teacher.dashboard.reports.subtitle', 'تقارير حضور الفصل', 'ar'),
	('teacher.dashboard.reports.subtitle', 'Class Attendance Reports', 'en'),
	('teacher.dashboard.reports.subtitle', 'Luokan läsnäoloraportit', 'fi'),
	('teacher.dashboard.reports.subtitle', 'Närvarorapporter för klassen', 'sv'),
	('teacher.dashboard.reports.title', 'ሪፖርቶች', 'am'),
	('teacher.dashboard.reports.title', 'التقارير', 'ar'),
	('teacher.dashboard.reports.title', 'View Reports', 'en'),
	('teacher.dashboard.reports.title', 'Raportit', 'fi'),
	('teacher.dashboard.reports.title', 'Rapporter', 'sv'),
	('teacher.dashboard.stats.absent', 'ዛሬ አልተገኙም', 'am'),
	('teacher.dashboard.stats.absent', 'الغائبون اليوم', 'ar'),
	('teacher.dashboard.stats.absent', 'Absent Today', 'en'),
	('teacher.dashboard.stats.absent', 'Poissa tänään', 'fi'),
	('teacher.dashboard.stats.absent', 'Frånvarande idag', 'sv'),
	('teacher.dashboard.stats.classes', 'የእኔ ክፍሎች', 'am'),
	('teacher.dashboard.stats.classes', 'فصولي', 'ar'),
	('teacher.dashboard.stats.classes', 'My Classes', 'en'),
	('teacher.dashboard.stats.classes', 'Luokkani', 'fi'),
	('teacher.dashboard.stats.classes', 'Mina klasser', 'sv'),
	('teacher.dashboard.stats.present', 'ዛሬ ተገኝተዋል', 'am'),
	('teacher.dashboard.stats.present', 'الحاضرون اليوم', 'ar'),
	('teacher.dashboard.stats.present', 'Present Today', 'en'),
	('teacher.dashboard.stats.present', 'Läsnä tänään', 'fi'),
	('teacher.dashboard.stats.present', 'Närvarande idag', 'sv'),
	('teacher.dashboard.stats.students', 'ጠቅላላ ተማሪዎች', 'am'),
	('teacher.dashboard.stats.students', 'إجمالي الطلاب', 'ar'),
	('teacher.dashboard.stats.students', 'Total Students', 'en'),
	('teacher.dashboard.stats.students', 'Opiskelijoita yhteensä', 'fi'),
	('teacher.dashboard.stats.students', 'Totalt antal studenter', 'sv'),
	('teacher.dashboard.takeAttendance.subtitle', 'ለክፍልዎ የQR ኮድ ይፍጠሩ', 'am'),
	('teacher.dashboard.takeAttendance.subtitle', 'أنشئ رمز QR لفصلك', 'ar'),
	('teacher.dashboard.takeAttendance.subtitle', 'Generate QR code for your class', 'en'),
	('teacher.dashboard.takeAttendance.subtitle', 'Luo QR-koodi luokallesi', 'fi'),
	('teacher.dashboard.takeAttendance.subtitle', 'Skapa en QR‑kod för din klass', 'sv'),
	('teacher.dashboard.takeAttendance.title', 'መገኘት ይመዝግቡ', 'am'),
	('teacher.dashboard.takeAttendance.title', 'تسجيل الحضور', 'ar'),
	('teacher.dashboard.takeAttendance.title', 'Take Attendance', 'en'),
	('teacher.dashboard.takeAttendance.title', 'Merkitse läsnäolo', 'fi'),
	('teacher.dashboard.takeAttendance.title', 'Registrera närvaro', 'sv'),
	('teacher.dashboard.title', 'የአስተማሪ ፓነል', 'am'),
	('teacher.dashboard.title', 'لوحة المعلم', 'ar'),
	('teacher.dashboard.title', 'Teacher Dashboard', 'en'),
	('teacher.dashboard.title', 'Opettajan hallintapaneeli', 'fi'),
	('teacher.dashboard.title', 'Lärarpanel', 'sv'),
	('teacher.email.button.refresh', 'እንደገና ይጫኑ', 'am'),
	('teacher.email.button.refresh', 'تحديث', 'ar'),
	('teacher.email.button.refresh', 'Refresh', 'en'),
	('teacher.email.button.refresh', 'Päivitä', 'fi'),
	('teacher.email.button.refresh', 'Uppdatera', 'sv'),
	('teacher.email.class_select.placeholder', 'ክፍል ይምረጡ', 'am'),
	('teacher.email.class_select.placeholder', 'اختر الفصل', 'ar'),
	('teacher.email.class_select.placeholder', 'Select class', 'en'),
	('teacher.email.class_select.placeholder', 'Valitse luokka', 'fi'),
	('teacher.email.class_select.placeholder', 'Välj klass', 'sv'),
	('teacher.email.error.classes', 'ክፍሎችን መጫን አልተቻለም: {reason}', 'am'),
	('teacher.email.error.classes', 'تعذر تحميل الفصول: {reason}', 'ar'),
	('teacher.email.error.classes', 'Failed to load classes: {reason}', 'en'),
	('teacher.email.error.classes', 'Luokkien lataus epäonnistui: {reason}', 'fi'),
	('teacher.email.error.classes', 'Kunde inte ladda klasser: {reason}', 'sv'),
	('teacher.email.error.students', 'ተማሪዎችን መጫን አልተቻለም: {reason}', 'am'),
	('teacher.email.error.students', 'تعذر تحميل الطلاب: {reason}', 'ar'),
	('teacher.email.error.students', 'Failed to load students: {reason}', 'en'),
	('teacher.email.error.students', 'Opiskelijoiden lataus epäonnistui: {reason}', 'fi'),
	('teacher.email.error.students', 'Kunde inte ladda studenter: {reason}', 'sv'),
	('teacher.email.loading.students', 'በመጫን ላይ...', 'am'),
	('teacher.email.loading.students', 'جارٍ تحميل الطلاب...', 'ar'),
	('teacher.email.loading.students', 'Loading...', 'en'),
	('teacher.email.loading.students', 'Ladataan...', 'fi'),
	('teacher.email.loading.students', 'Laddar...', 'sv'),
	('teacher.email.subtitle', 'የተማሪዎች ኢሜይል ለማየት ክፍል ይምረጡ', 'am'),
	('teacher.email.subtitle', 'اختر فصلاً لعرض بريد الطلاب', 'ar'),
	('teacher.email.subtitle', 'Select a class to view student emails.', 'en'),
	('teacher.email.subtitle', 'Valitse luokka nähdäksesi opiskelijoiden sähköpostit.', 'fi'),
	('teacher.email.subtitle', 'Välj en klass för att se studenternas e‑postadresser.', 'sv'),
	('teacher.email.table.column.email', 'ኢሜይል', 'am'),
	('teacher.email.table.column.email', 'البريد الإلكتروني', 'ar'),
	('teacher.email.table.column.email', 'Email', 'en'),
	('teacher.email.table.column.email', 'Sähköposti', 'fi'),
	('teacher.email.table.column.email', 'E‑post', 'sv'),
	('teacher.email.table.column.student', 'ተማሪ', 'am'),
	('teacher.email.table.column.student', 'الطالب', 'ar'),
	('teacher.email.table.column.student', 'Student', 'en'),
	('teacher.email.table.column.student', 'Opiskelija', 'fi'),
	('teacher.email.table.column.student', 'Student', 'sv'),
	('teacher.email.title', 'ኢሜይል', 'am'),
	('teacher.email.title', 'البريد الإلكتروني', 'ar'),
	('teacher.email.title', 'Email', 'en'),
	('teacher.email.title', 'Sähköposti', 'fi'),
	('teacher.email.title', 'E‑post', 'sv'),
	('teacher.excuse.cancel', 'ይቅር', 'am'),
	('teacher.excuse.cancel', 'إلغاء', 'ar'),
	('teacher.excuse.cancel', 'Cancel', 'en'),
	('teacher.excuse.cancel', 'Peruuta', 'fi'),
	('teacher.excuse.cancel', 'Avbryt', 'sv'),
	('teacher.excuse.hint', 'ተማሪው ለምን ተሰርዟል ይግለጹ:', 'am'),
	('teacher.excuse.hint', 'اشرح سبب عذر الطالب:', 'ar'),
	('teacher.excuse.hint', 'Write the reason why this student is excused:', 'en'),
	('teacher.excuse.hint', 'Kirjoita syy, miksi opiskelija on vapautettu:', 'fi'),
	('teacher.excuse.hint', 'Ange orsaken till att studenten är ursäktad:', 'sv'),
	('teacher.excuse.save', 'አስቀምጥ', 'am'),
	('teacher.excuse.save', 'حفظ', 'ar'),
	('teacher.excuse.save', 'Save', 'en'),
	('teacher.excuse.save', 'Tallenna', 'fi'),
	('teacher.excuse.save', 'Spara', 'sv'),
	('teacher.excuse.student', 'ተማሪ: {name} ({email})', 'am'),
	('teacher.excuse.student', 'الطالب: {name} ({email})', 'ar'),
	('teacher.excuse.student', 'Student: {name} ({email})', 'en'),
	('teacher.excuse.student', 'Opiskelija: {name} ({email})', 'fi'),
	('teacher.excuse.student', 'Student: {name} ({email})', 'sv'),
	('teacher.excuse.title', 'የመብት ምክንያት', 'am'),
	('teacher.excuse.title', 'سبب العذر', 'ar'),
	('teacher.excuse.title', 'Excuse Reason', 'en'),
	('teacher.excuse.title', 'Vapautuksen syy', 'fi'),
	('teacher.excuse.title', 'Orsak till frånvaro', 'sv'),
	('teacher.fallback.name', 'ስም', 'am'),
	('teacher.fallback.name', 'الاسم', 'ar'),
	('teacher.fallback.name', 'Name', 'en'),
	('teacher.fallback.name', 'Nimi', 'fi'),
	('teacher.fallback.name', 'Namn', 'sv'),
	('teacher.reports.alert.selectSession', 'መጀመሪያ ሴሽን ይምረጡ።', 'am'),
	('teacher.reports.alert.selectSession', 'يرجى اختيار الجلسة أولاً.', 'ar'),
	('teacher.reports.alert.selectSession', 'Select a session first.', 'en'),
	('teacher.reports.alert.selectSession', 'Valitse ensin istunto.', 'fi'),
	('teacher.reports.alert.selectSession', 'Välj en session först.', 'sv'),
	('teacher.reports.error.export', 'መላክ አልተሳካም:', 'am'),
	('teacher.reports.error.export', 'فشل التصدير:', 'ar'),
	('teacher.reports.error.export', 'Export failed:', 'en'),
	('teacher.reports.error.export', 'Vienti epäonnistui:', 'fi'),
	('teacher.reports.error.export', 'Export misslyckades:', 'sv'),
	('teacher.reports.error.loadClasses', 'ክፍሎችን መጫን አልተቻለም: {error}', 'am'),
	('teacher.reports.error.loadClasses', 'تعذر تحميل الفصول: {error}', 'ar'),
	('teacher.reports.error.loadClasses', 'Failed to load classes: {error}', 'en'),
	('teacher.reports.error.loadClasses', 'Luokkien lataus epäonnistui: {error}', 'fi'),
	('teacher.reports.error.loadClasses', 'Kunde inte ladda klasser: {error}', 'sv'),
	('teacher.reports.error.loadReport', 'ሪፖርት መጫን አልተቻለም:', 'am'),
	('teacher.reports.error.loadReport', 'تعذر تحميل التقرير:', 'ar'),
	('teacher.reports.error.loadReport', 'Report failed:', 'en'),
	('teacher.reports.error.loadReport', 'Raportin lataus epäonnistui:', 'fi'),
	('teacher.reports.error.loadReport', 'Kunde inte ladda rapport:', 'sv'),
	('teacher.reports.error.loadSessions', 'ሴሽኖችን መጫን አልተቻለም: {error}', 'am'),
	('teacher.reports.error.loadSessions', 'تعذر تحميل الجلسات: {error}', 'ar'),
	('teacher.reports.error.loadSessions', 'Failed to load sessions: {error}', 'en'),
	('teacher.reports.error.loadSessions', 'Istuntojen lataus epäonnistui: {error}', 'fi'),
	('teacher.reports.error.loadSessions', 'Kunde inte ladda sessioner: {error}', 'sv'),
	('teacher.reports.export.success.csv', 'CSV ተቀምጧል ወደ:', 'am'),
	('teacher.reports.export.success.csv', 'تم حفظ ملف CSV في:', 'ar'),
	('teacher.reports.export.success.csv', 'CSV saved to:', 'en'),
	('teacher.reports.export.success.csv', 'CSV tallennettu sijaintiin:', 'fi'),
	('teacher.reports.export.success.csv', 'CSV sparad till:', 'sv'),
	('teacher.reports.export.success.pdf', 'PDF ተቀምጧል ወደ:', 'am'),
	('teacher.reports.export.success.pdf', 'تم حفظ ملف PDF في:', 'ar'),
	('teacher.reports.export.success.pdf', 'PDF saved to:', 'en'),
	('teacher.reports.export.success.pdf', 'PDF tallennettu sijaintiin:', 'fi'),
	('teacher.reports.export.success.pdf', 'PDF sparad till:', 'sv'),
	('teacher.reports.filechooser.csv.name', 'teacher_report.csv', 'am'),
	('teacher.reports.filechooser.csv.name', 'teacher_report.csv', 'ar'),
	('teacher.reports.filechooser.csv.name', 'teacher-report.csv', 'en'),
	('teacher.reports.filechooser.csv.name', 'opettaja-raportti.csv', 'fi'),
	('teacher.reports.filechooser.csv.name', 'lararrapport.csv', 'sv'),
	('teacher.reports.filechooser.csv.title', 'የCSV ሪፖርት ያስቀምጡ', 'am'),
	('teacher.reports.filechooser.csv.title', 'حفظ تقرير CSV', 'ar'),
	('teacher.reports.filechooser.csv.title', 'Save CSV Report', 'en'),
	('teacher.reports.filechooser.csv.title', 'Tallenna CSV-raportti', 'fi'),
	('teacher.reports.filechooser.csv.title', 'Spara CSV‑rapport', 'sv'),
	('teacher.reports.filechooser.pdf.name', 'teacher_report.pdf', 'am'),
	('teacher.reports.filechooser.pdf.name', 'teacher_report.pdf', 'ar'),
	('teacher.reports.filechooser.pdf.name', 'teacher-report.pdf', 'en'),
	('teacher.reports.filechooser.pdf.name', 'opettaja-raportti.pdf', 'fi'),
	('teacher.reports.filechooser.pdf.name', 'lararrapport.pdf', 'sv'),
	('teacher.reports.filechooser.pdf.title', 'የPDF ሪፖርት ያስቀምጡ', 'am'),
	('teacher.reports.filechooser.pdf.title', 'حفظ تقرير PDF', 'ar'),
	('teacher.reports.filechooser.pdf.title', 'Save PDF Report', 'en'),
	('teacher.reports.filechooser.pdf.title', 'Tallenna PDF-raportti', 'fi'),
	('teacher.reports.filechooser.pdf.title', 'Spara PDF‑rapport', 'sv'),
	('teacher.reports.load', 'ሪፖርት ይጫኑ', 'am'),
	('teacher.reports.load', 'تحميل التقرير', 'ar'),
	('teacher.reports.load', 'Load Report', 'en'),
	('teacher.reports.load', 'Lataa raportti', 'fi'),
	('teacher.reports.load', 'Ladda rapport', 'sv'),
	('teacher.reports.select.class', 'ክፍል ይምረጡ', 'am'),
	('teacher.reports.select.class', 'اختر الفصل', 'ar'),
	('teacher.reports.select.class', 'Select class', 'en'),
	('teacher.reports.select.class', 'Valitse luokka', 'fi'),
	('teacher.reports.select.class', 'Välj klass', 'sv'),
	('teacher.reports.select.session', 'ሴሽን ይምረጡ', 'am'),
	('teacher.reports.select.session', 'اختر الجلسة', 'ar'),
	('teacher.reports.select.session', 'Select session', 'en'),
	('teacher.reports.select.session', 'Valitse istunto', 'fi'),
	('teacher.reports.select.session', 'Välj session', 'sv'),
	('teacher.reports.session.code', '(ኮድ: {code})', 'am'),
	('teacher.reports.session.code', '(الرمز: {code})', 'ar'),
	('teacher.reports.session.code', '(code: {code})', 'en'),
	('teacher.reports.session.code', '(koodi: {code})', 'fi'),
	('teacher.reports.session.code', '(kod: {code})', 'sv'),
	('teacher.reports.session.default', 'ሴሽን {id}', 'am'),
	('teacher.reports.session.default', 'جلسة {id}', 'ar'),
	('teacher.reports.session.default', 'Session {id}', 'en'),
	('teacher.reports.session.default', 'Istunto {id}', 'fi'),
	('teacher.reports.session.default', 'Session {id}', 'sv'),
	('teacher.reports.stats.absent', 'አልተገኘም: {count}', 'am'),
	('teacher.reports.stats.absent', 'غائب: {count}', 'ar'),
	('teacher.reports.stats.absent', 'Absent: {count}', 'en'),
	('teacher.reports.stats.absent', 'Poissa: {count}', 'fi'),
	('teacher.reports.stats.absent', 'Frånvarande: {count}', 'sv'),
	('teacher.reports.stats.excused', 'ተሰርዟል: {count}', 'am'),
	('teacher.reports.stats.excused', 'معذور: {count}', 'ar'),
	('teacher.reports.stats.excused', 'Excused: {count}', 'en'),
	('teacher.reports.stats.excused', 'Vapautettu: {count}', 'fi'),
	('teacher.reports.stats.excused', 'Ursäktade: {count}', 'sv'),
	('teacher.reports.stats.present', 'ተገኝቷል: {count}', 'am'),
	('teacher.reports.stats.present', 'حاضر: {count}', 'ar'),
	('teacher.reports.stats.present', 'Present: {count}', 'en'),
	('teacher.reports.stats.present', 'Läsnä: {count}', 'fi'),
	('teacher.reports.stats.present', 'Närvarande: {count}', 'sv'),
	('teacher.reports.stats.rate', 'መገኘት: {rate}%', 'am'),
	('teacher.reports.stats.rate', 'نسبة الحضور: {rate}%', 'ar'),
	('teacher.reports.stats.rate', 'Rate: {rate}%', 'en'),
	('teacher.reports.stats.rate', 'Prosentti: {rate}%', 'fi'),
	('teacher.reports.stats.rate', 'Procent: {rate}%', 'sv'),
	('teacher.reports.subtitle', 'የሴሽን ሪፖርቶች (መገኘት ስታቲስቲክስ + ዝርዝር)', 'am'),
	('teacher.reports.subtitle', 'تقارير الجلسات (إحصائيات + تفاصيل)', 'ar'),
	('teacher.reports.subtitle', 'Session reports (attendance stats + list)', 'en'),
	('teacher.reports.subtitle', 'Istuntoraportit (läsnäolotilastot + lista)', 'fi'),
	('teacher.reports.subtitle', 'Sessionsrapporter (närvarostatistik + lista)', 'sv'),
	('teacher.reports.table.email', 'ኢሜይል', 'am'),
	('teacher.reports.table.email', 'البريد الإلكتروني', 'ar'),
	('teacher.reports.table.email', 'Email', 'en'),
	('teacher.reports.table.email', 'Sähköposti', 'fi'),
	('teacher.reports.table.email', 'E‑post', 'sv'),
	('teacher.reports.table.status', 'ሁኔታ', 'am'),
	('teacher.reports.table.status', 'الحالة', 'ar'),
	('teacher.reports.table.status', 'Status', 'en'),
	('teacher.reports.table.status', 'Tila', 'fi'),
	('teacher.reports.table.status', 'Status', 'sv'),
	('teacher.reports.table.student', 'ተማሪ', 'am'),
	('teacher.reports.table.student', 'الطالب', 'ar'),
	('teacher.reports.table.student', 'Student', 'en'),
	('teacher.reports.table.student', 'Opiskelija', 'fi'),
	('teacher.reports.table.student', 'Student', 'sv'),
	('teacher.reports.title', 'ሪፖርቶች', 'am'),
	('teacher.reports.title', 'التقارير', 'ar'),
	('teacher.reports.title', 'Reports', 'en'),
	('teacher.reports.title', 'Raportit', 'fi'),
	('teacher.reports.title', 'Rapporter', 'sv'),
	('teacher.sidebar.logout', 'ውጣ', 'am'),
	('teacher.sidebar.logout', 'تسجيل الخروج', 'ar'),
	('teacher.sidebar.logout', 'Logout', 'en'),
	('teacher.sidebar.logout', 'Kirjaudu ulos', 'fi'),
	('teacher.sidebar.logout', 'Logga ut', 'sv'),
	('teacher.sidebar.menu.dashboard', 'እይታ', 'am'),
	('teacher.sidebar.menu.dashboard', 'الرئيسية', 'ar'),
	('teacher.sidebar.menu.dashboard', 'Dashboard', 'en'),
	('teacher.sidebar.menu.dashboard', 'Hallintapaneeli', 'fi'),
	('teacher.sidebar.menu.dashboard', 'Översikt', 'sv'),
	('teacher.sidebar.menu.email', 'ኢሜይል', 'am'),
	('teacher.sidebar.menu.email', 'البريد الإلكتروني', 'ar'),
	('teacher.sidebar.menu.email', 'Email', 'en'),
	('teacher.sidebar.menu.email', 'Sähköposti', 'fi'),
	('teacher.sidebar.menu.email', 'E‑post', 'sv'),
	('teacher.sidebar.menu.reports', 'ሪፖርቶች', 'am'),
	('teacher.sidebar.menu.reports', 'التقارير', 'ar'),
	('teacher.sidebar.menu.reports', 'Reports', 'en'),
	('teacher.sidebar.menu.reports', 'Raportit', 'fi'),
	('teacher.sidebar.menu.reports', 'Rapporter', 'sv'),
	('teacher.sidebar.menu.take_attendance', 'መገኘት ይመዝግቡ', 'am'),
	('teacher.sidebar.menu.take_attendance', 'تسجيل الحضور', 'ar'),
	('teacher.sidebar.menu.take_attendance', 'Take Attendance', 'en'),
	('teacher.sidebar.menu.take_attendance', 'Merkitse läsnäolo', 'fi'),
	('teacher.sidebar.menu.take_attendance', 'Registrera närvaro', 'sv'),
	('teacher.sidebar.title', 'የአስተማሪ ፓነል', 'am'),
	('teacher.sidebar.title', 'لوحة المعلم', 'ar'),
	('teacher.sidebar.title', 'Teacher Panel', 'en'),
	('teacher.sidebar.title', 'Opettajan paneeli', 'fi'),
	('teacher.sidebar.title', 'Lärarpanel', 'sv');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
