apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: attendance-app
type: Opaque
stringData:
  MYSQL_DATABASE: classroom_attendance
  MYSQL_USER: db_user
  MYSQL_PASSWORD: db_password
  MYSQL_ROOT_PASSWORD: rootpassword
  DB_URL: jdbc:mysql://mysql-service:3306/classroom_attendance?serverTimezone=UTC